version: "3"
services:
  #loki:
  #  image: grafana/loki:k178-d1cdf79
  #  restart: always
  #  networks:
  #    - main

  grafana:
    image: grafana/grafana-oss
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana-data:/var/lib/grafana
    user: "root"
    networks:
      - main

  prometheus:
    image: prom/prometheus:v2.48.0
    restart: always
    user: root
    volumes:
      - ./prometheus-config:/etc/prometheus
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - main

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./back/migrations-folder:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - main

  postgres-exporter:
    image: bitnami/postgres-exporter
    restart: always
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4:8.0
    restart: always
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    user: "root"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_DISABLE_POSTFIX=true
    networks:
      - main

  front:
    build:
      context: front
      dockerfile: Dockerfile
    restart: always
    networks:
      - main

  back:
    build:
      context: back
      dockerfile: Dockerfile
    restart: always
    networks:
      - main

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - "${PORT_NGINX:-8888}:80"
    networks:
      - main

networks:
  main:
    driver: bridge
