global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: back
    static_configs:
      - targets: ['back:4000']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
