FROM node:21-alpine
 
RUN npm install -g pnpm
 
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
 
COPY . .
 
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--port", "3000", "--host"]
